### ISSUE TITLE
Link to CDN causing responsive (phone) to overflow

### ISSUE THREAD

**Issue by techtolentino** [ahmedtarek2134/grid.css#1]
Hey 👋 

Just wanted to bring to your attention that on mobile devices, the link to the CDN is breaking the responsiveness of your site.

![gridcss ga--utm_content buffer05609 utm_medium social utm_source twitter com utm_campaign buffer iphone 5 1](https://user-images.githubusercontent.com/6276074/30331817-6682e940-979e-11e7-9a8b-adb98cdbfe05.png)

![gridcss ga--utm_content buffer05609 utm_medium social utm_source twitter com utm_campaign buffer iphone 5 2](https://user-images.githubusercontent.com/6276074/30331825-6c2005cc-979e-11e7-8271-f824feaa6a69.png)

Looks like it can be addressed with `word-wrap: break-word` or by just using `<a href="link-to-cdn">Link to CDN</a>` - something like that.

👏  Nice work!

**Comment by ahmedtarek2134** [comment]
Thank you so much for the feedback, I will actually be totally re-coding and designing the website so it should be up this weekend hopefully. <3
